import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "@/app/globals.css";
import Sidebar from "@/components/sidebar";
import { poppins } from '@/app/ui/fonts';
// const inter = Inter({ subsets: ["latin"] });



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.className}>
      <body className={`${poppins.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
